alias gitl='git log --graph --pretty=format:'\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ci) %C(bold blue)<%an>%Creset%n'\'''
alias gitpwl='git push --force-with-lease'
alias grep='grep --color=auto'
alias infraup='COMPOSE_PROJECT_NAME="" docker-compose -f infrastructure/tools/docker-compose.yml up -d'
alias fi='cd ~/dev/financement'
alias ws='docker-compose exec ws bash'
alias ram='sudo swapoff -a && sudo swapon -a && sudo sysctl vm.drop_caches=3'
alias wsrmc='sudo rm -Rf /home/eritrang/dev/financement/ws/src/app/cache/*'
alias hlp='cat ~/.bash_aliases'
alias phpstorm='~/PhpStorm-203.7148.74/bin/phpstorm.sh'
alias lfi='sudo /etc/init.d/apache2 stop && wsrmc && cd /home/eritrang/dev/financement && docker compose up'
alias lft='sudo /etc/init.d/apache2 stop && wsrmc && cd /home/eritrang/dev/financement && cd crm && COMPOSE_PROJECT_NAME="" docker compose -f infrastructure/tools/docker-compose.yml up -d && cd .. && docker compose up'
alias lftc='sudo /etc/init.d/apache2 stop && cd /home/eritrang/dev/financement && cd crm && COMPOSE_PROJECT_NAME="" docker compose -f infrastructure/tools/docker-compose.yml up -d && cd .. && docker compose up'
alias lf='wsrmc && cd /home/eritrang/dev/financement && COMPOSE_PROJECT_NAME="" docker compose -f infrastructure/tools/docker-compose.yml up -d && docker compose up'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias up='docker-compose -f docker-compose-dev.yml up -d'
alias ddip='sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1'
